name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t my-app:${IMAGE_TAG} .
        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
        docker tag my-app:${IMAGE_TAG} $DOCKERHUB_USERNAME/my-app:${IMAGE_TAG}
        docker push $DOCKERHUB_USERNAME/my-app:${IMAGE_TAG}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "${KUBE_CONFIG}" > kubeconfig.yaml
        kubectl apply -f clusters/<cluster-name>/kustomization.yaml

